# Generated by Django 6.0.3 on 2026-03-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='model_version',
            field=models.CharField(default='hybrid-v1', max_length=30),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='customer_id',
            field=models.IntegerField(unique=True),
        ),
    ]
