# Generated by Django 6.0.1 on 2026-03-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	initial = True

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name="UserProfile",
			fields=[
				("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("role", models.CharField(choices=[("customer", "Customer"), ("staff", "Staff"), ("manager", "Manager"), ("admin", "Admin")], default="customer", max_length=20)),
				("customer_id", models.IntegerField(blank=True, null=True)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
				("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="gateway_profile", to=settings.AUTH_USER_MODEL)),
			],
		),
	]
